services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: movie-buzz-zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - movie-buzz-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: movie-buzz-kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - movie-buzz-network

  postgres:
    image: postgres:16
    container_name: movie-buzz-postgres
    hostname: postgres
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: movies
      POSTGRES_PASSWORD: movies
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - movie-buzz-network

  spark:
    build: ./spark
    container_name: movie-buzz-spark
    hostname: spark
    depends_on:
      - kafka
      - postgres
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./streaming:/opt/spark/jobs
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    networks:
      - movie-buzz-network

  grafana:
    image: grafana/grafana-oss:10.4.2
    container_name: movie-buzz-grafana
    hostname: grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - movie-buzz-network

volumes:
  grafana_data:
  postgres_data:

networks:
  movie-buzz-network: