{
 "title": "My dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Buzz Score",
   "type": "gauge",
   "description": "Real-time average buzz score representing the overall popularity level of movies across all streaming events.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  AVG(buzz_score) AS value\r\nFROM movie_events\r\nWHERE $__timeFilter(event_time)\r\n"
    }
   ]
  },
  {
   "title": "Platform Engagement",
   "type": "bargauge",
   "description": "Comparison of streaming engagement across different platforms (Netflix, Prime Video, Disney+).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  platform,\r\n  COUNT(*) AS events\r\nFROM movie_events\r\nGROUP BY platform\r\nORDER BY events DESC"
    }
   ]
  },
  {
   "title": "Events by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  region,\r\n  COUNT(*) AS events\r\nFROM movie_events\r\nGROUP BY region"
    }
   ]
  },
  {
   "title": "Top Movies Buzz",
   "type": "barchart",
   "description": "Ranking of the most popular movies based on user interactions generated in the streaming pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  title,\r\n  COUNT(*) AS events\r\nFROM movie_events\r\nGROUP BY title\r\nORDER BY events DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Streaming Events per Minute",
   "type": "timeseries",
   "description": "Real-time visualization of streaming activity showing the number of events processed per minute from the Kafka pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(event_time,'1m') AS time,\r\n  COUNT(*) AS value\r\nFROM movie_events\r\nWHERE $__timeFilter(event_time)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  }
 ]
}